### ISSUE TITLE
Implement -c/--copy flag

### ISSUE THREAD

**Issue by ZNielsen** [ZatchBo/numconverter#8]
When provided with the `-c` or `--copy` flag, the output of `numconverter` should be copied to the clipboard.

Ideally, this would work on all platforms without the user needing to do anything different.

This addition should play nice with the `--silent` flag; no output should be printed, but the result should be copied to the clipboard.

**Comment by Jonathas-Conceicao** [comment]
I was just playing around this one and I've implemented the feature using [rust-clipboard](https://github.com/aweinstock314/rust-clipboard).

I did, however, run into an [know issue](https://github.com/aweinstock314/rust-clipboard/issues/61) when testing on Linux, any suggestion on how to address the persistency?

**Comment by ZNielsen** [comment]
Awesome!  I had tinkered with rust-clipboard, but never got it to work.  That issue you linked would definitely be why.

It sounds like we would need to implement a daemon or service to have a persistent clipboard.  Off the top of my head, I would probably have `numconverter` spin off a persistent child process when passed in the -c flag.  For all future calls containing the -c flag, we would need to either kill the old child process and relaunch the one for this call, or refresh the data sitting in that process.

**Comment by ZNielsen** [comment]
If we need to implement a background process to hold the clipboard anyway, we may as well add a `--from-clipboard` option to `numconverter` as well.  Doesn't have to be in the same PR.  If you end up implementing a background process, I'll add the option as another feature ticket.

**Comment by ZNielsen** [comment]
@Jonathas-Conceicao - would you like me to assign this issue to you?

**Comment by Jonathas-Conceicao** [comment]
Sure, I should have some free time over the next feel days and I intend to finish working on this one.

**Comment by Jonathas-Conceicao** [comment]
@ZNielsen I have now on my [fork](https://github.com/Jonathas-Conceicao/numconverter/tree/topic/copy_flag) a functional implementation for this feature. I would like to discuse with you a feel things now:

- First a quick one, is there any particular config for rust fmt you've been used for this project? If so you should add a .rustfmt.toml to the repository. And if you're not currently using any I think one should be defined.

- I would like to know what do you think about my solution to the persistence problem on X11's clipboard:
1. Since on linux we need some extra handling for the clipboard, I've done it in a function with conditional compilation, a simple call to the clipboard crate when 'not on linux', and a different build for when running on Linux;
2. When building for linux I have used nix::unistd::fork to create a child process that will have the ownership to the clipboard content while the parrent can freely finish;
3. The child process I aim at keep alive for as long as it has ownership over the clipboard content, once someone else overwrite's it, the child process can terminate;
4. Since rust-clipboard itself doesn't give-me any tools to actually know when I don't own clipboard content anymore, I decided to use for the Linux implementation the x11_clipboard crate directly, this way I can access the connection used between my application and the X server and I can check from time to time (every second currently) if I still own the clipboard selection, once I don't anymore the child process job is done.

- Once I've done some code cleanup and we have discussed the fmt details I've mentioned above I can create a PR so we can discuss code in more detail;

- Lastly, about the --from-clipboard flag, that should be simple, since reading from clipboard the a bit more straightforward on rust-clip.

**Comment by ZNielsen** [comment]
I'll look into some different `.rustfmt.toml` options.  I usually find that auto-formatters don't have the nuance I'm looking for, but I probably should include one now that this project is growing past a single contributor.

That solution sounds great.  I like that the background process isn't hanging around if the clipboard has changed.  I think it's pretty normal to have to have some compiler level flags to differentiate between Windows/Unix platforms.  Even though I don't really like that type of solution in general, I don't think there is any avoiding it for cross-platform work.

I'll drop another comment here when I pick out a formatter, but I'm fine having to clean up when that decision is made.  Don't let the format hold you up if that's all you are waiting for.
